//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Tees = new HashSet<Tee>();
        }
    
        public int CourseId { get; set; }
        public int FacilityId { get; set; }
        public string Name { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual ICollection<Tee> Tees { get; set; }
    }
}
