//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundDetail
    {
        public int RoundDetailId { get; set; }
        public int RoundId { get; set; }
        public int HoleId { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Putts { get; set; }
        public Nullable<bool> GIR { get; set; }
        public Nullable<bool> FIR { get; set; }
    
        public virtual Round Round { get; set; }
    }
}
