//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        public Round()
        {
            this.RoundDetails = new HashSet<RoundDetail>();
        }
    
        public int RoundId { get; set; }
        public int FacilityId { get; set; }
        public int CourseId { get; set; }
        public int TeeId { get; set; }
        public System.DateTime Date { get; set; }
        public int TotalScore { get; set; }
    
        public virtual ICollection<RoundDetail> RoundDetails { get; set; }
    }
}
