//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GolfStatTrackerEntities : DbContext
    {
        public GolfStatTrackerEntities()
            : base("name=GolfStatTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<Golfer> Golfers { get; set; }
        public virtual DbSet<Hole> Holes { get; set; }
        public virtual DbSet<RoundDetail> RoundDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tee> Tees { get; set; }
        public virtual DbSet<Round> Rounds { get; set; }
    }
}
