//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tee
    {
        public Tee()
        {
            this.Holes = new HashSet<Hole>();
            this.Courses = new HashSet<Cours>();
        }
    
        public int TeeId { get; set; }
        public int CourseId { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Slope { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> Yardage { get; set; }
        public int FacilityId { get; set; }
    
        public virtual ICollection<Hole> Holes { get; set; }
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
